### ISSUE TITLE
Crash (java.lang.IllegalArgumentException: Empty string not allowed)

### ISSUE THREAD

**Issue by Wolftein** [OpenModularTurretsTeam/OpenModularTurrets#132]
```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 15/07/15 15:41
Description: Exception ticking world

java.lang.IllegalArgumentException: Empty string not allowed
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:23)
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:105)
        at openmodularturrets.tileentity.turretbase.TurretBase.writeToNBT_OpenComputers(TurretBase.java:205)
        at li.cil.oc.common.asm.template.StaticSimpleEnvironment.writeToNBT(StaticSimpleEnvironment.java:74)
        at openmodularturrets.tileentity.turretbase.TurretBase.func_145841_b(TurretBase.java:57)
        at openmodularturrets.tileentity.turretbase.TurretBase.func_145844_m(TurretBase.java:187)
        at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:629)
        at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:614)
        at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:84)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:23)
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:105)
        at openmodularturrets.tileentity.turretbase.TurretBase.writeToNBT_OpenComputers(TurretBase.java:205)
        at li.cil.oc.common.asm.template.StaticSimpleEnvironment.writeToNBT(StaticSimpleEnvironment.java:74)
        at openmodularturrets.tileentity.turretbase.TurretBase.func_145841_b(TurretBase.java:57)
        at openmodularturrets.tileentity.turretbase.TurretBase.func_145844_m(TurretBase.java:187)
        at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:629)
        at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:614)
        at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:84)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287)
-- Affected level --
Details:
        Level name: world
        All players: 1 total; [EntityPlayerMP['Chelusa'/516, l='world', x=-52,09, y=63,00, z=-111,56](Chelusa at -52.08967315656203,63.0,-111.564$
        Chunk stats: ServerChunkCache: 271 Drop: 0
        Level seed: 757798792
        Level generator: ID 00 - default, ver 1. Features enabled: true
        Level generator options:
        Level spawn location: World: (-63,67,-110), Chunk: (at 1,4,2 in -4,-7; contains blocks -64,0,-112 to -49,255,-97), Region: (-1,-1; contai$
        Level time: 9022433 game time, 10211310 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 36517 (now: false), thunder time: 15309 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
        Minecraft Version: 1.7.10
        KCauldron Version: pw.prok:KCauldron:1.7.10-1481.145
        Operating System: Linux (amd64) version 3.19.0-15-generic
        Java Version: 1.8.0_45, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 3774829672 bytes (3599 MB) / 4268818432 bytes (4071 MB) up to 6416302080 bytes (6119 MB)
        JVM Flags: 13 total; -Xms4G -Xmx6G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:+CMSParallelRemarkEnabled$
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 40 mods loaded, 40 mods active
```

**Comment by Keridos** [comment]
When did this happen, what did you do, can you replicate it?

**Comment by Wolftein** [comment]
Yes, one of my admins used World editor to cut and paste an area. When he accidentally cut half of the turret (Without the block which gave power to the turret) and now everytime the chunk loads that error won't let us start the server.

**Comment by Poenjabiesous** [comment]
That would be because the turret itself stores a reference to the turret base it was placed on, which no longer exists in it's context (because of the copy paste).

**Comment by Keridos** [comment]
He can simply use mcedit to delete the corresponding turret, but we can maybe add a check there. But I am not certain why it crashes there and the crashlog tells something about OC.

For some reason you managed to corrupt the NBT data on the turret itself, it has no owner apparently. Without external tools this should not be possible as far as I know.

I got an idea though: Did you copy the chunk to a completely new world and was the old version run on an older OMT version? If yes, then probably the owner to uuid conversion failed and it set the owner to "" or something like that and that causes it to crash.

**Comment by Wolftein** [comment]
I will try to ask him more information about it, he told me he copied and pasted the same chunk next to it and then the server crashed. I had to remove the mod, turn on the server and let cauldron remove all references to OMT.

**Comment by Keridos** [comment]
That is odd, that should not cause it to crash. For some reason it told that the owner was an empty string, but that would've crashed the old bases as well. Anyway I am writing a small fix that may fix that, but I am not sure what the actual cause of the crash was. The fix should fix the crash, but the turretbase may be unusable. @Poenjabiesous We could delete/drop turretbases with no valid owner as well to prevent something like this from happening at all. A TurretBase without an owner makes no sense either.

**Comment by Poenjabiesous** [comment]
Yes, we can do that. Under normal circumstances something like this will never happen; It's clear the NBT data was corrupted in this instance by copy/pasting the chunk (Not sure why the world editor would do that).

We can add a check that if the owner name is empty, we drop the base. We should to that check in the all the writeToNBT methods, as it seems like it's where the excpetion comes from (Can't add an empty string to NBT data).

**Comment by Keridos** [comment]
We actually should do that in the readFromNBT function, i can pretty much rewrite this now.
