### ISSUE TITLE
A TileEntity leverTileEntity(openmodularturrets.tileentity.LeverTileEntity) has thrown an exception during loading

### ISSUE THREAD

**Issue by Wolftein** [OpenModularTurretsTeam/OpenModularTurrets#146]
Suddently my server started to spam this issue.

```
[03:14:36] [Server thread/ERROR] [FML/]: A TileEntity leverTileEntity(openmodularturrets.tileentity.LeverTileEntity) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
        at openmodularturrets.tileentity.LeverTileEntity.func_145839_a(LeverTileEntity.java:63) ~[LeverTileEntity.class:?]
        at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:124) [aor.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:525) [aqk.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) [ChunkIOProvider.class:1.7.10-1481.148]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-1481.148]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:1.7.10-1481.148]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:1.7.10-1481.148]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:1.7.10-1481.148]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:184) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:157) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:280) [ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:751) [ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:677) [ahb.class:?]
        at net.minecraft.world.World.func_147453_f(World.java:4573) [ahb.class:?]
        at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:161) [aor.class:?]
        at mekanism.common.tile.TileEntityBasicBlock.onChunkLoad(TileEntityBasicBlock.java:95) [TileEntityBasicBlock.class:?]
        at mekanism.common.Mekanism.onChunkLoad(Mekanism.java:1340) [Mekanism.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_171_Mekanism_onChunkLoad_Load.invoke(.dynamic) [?:1.7.10-1481.148]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1481.148]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:1.7.10-1481.148]
        at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1022) [apx.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) [ChunkIOProvider.class:1.7.10-1481.148]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-1481.148]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:1.7.10-1481.148]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:1.7.10-1481.148]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:1.7.10-1481.148]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:184) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:157) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:280) [ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:751) [ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:677) [ahb.class:?]
        at net.minecraft.world.World.func_147453_f(World.java:4565) [ahb.class:?]
        at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:161) [aor.class:?]
        at mekanism.common.tile.TileEntityBasicBlock.onChunkLoad(TileEntityBasicBlock.java:95) [TileEntityBasicBlock.class:?]
        at mekanism.common.Mekanism.onChunkLoad(Mekanism.java:1340) [Mekanism.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_171_Mekanism_onChunkLoad_Load.invoke(.dynamic) [?:1.7.10-1481.148]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1481.148]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:1.7.10-1481.148]
        at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1022) [apx.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) [ChunkIOProvider.class:1.7.10-1481.148]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-1481.148]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:1.7.10-1481.148]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:1.7.10-1481.148]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:1.7.10-1481.148]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:184) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:157) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:280) [ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:751) [ahb.class:?]
        at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:39) [ahr.class:?]
        at net.minecraft.world.World.func_72865_a(World.java:4003) [ahb.class:?]
        at net.minecraft.pathfinding.PathNavigate.func_75494_a(SourceFile:91) [vv.class:?]
        at thaumcraft.common.entities.ai.pech.AIPechItemEntityGoto.func_75249_e(AIPechItemEntityGoto.java:96) [AIPechItemEntityGoto.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94) [uj.class:?]
        at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:582) [sw.class:?]
        at thaumcraft.common.entities.monster.EntityPech.func_70619_bc(EntityPech.java:674) [EntityPech.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2066) [sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388) [sw.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:36) [yg.class:?]
        at thaumcraft.common.entities.monster.EntityPech.func_70636_d(EntityPech.java:229) [EntityPech.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1899) [sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213) [sw.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:41) [yg.class:?]
        at thaumcraft.common.entities.monster.EntityPech.func_70071_h_(EntityPech.java:663) [EntityPech.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2655) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2607) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2423) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by Keridos** [comment]
Which version of the mod are you using? I cannot find any issue within the source that could cause that. It rather looks like some weird bug with either forge or a world corruption issue.

**Comment by Wolftein** [comment]
I'm currently using OpenModularTurrets 2.0.1 151 with Cauldron (1.7.10 forge build 1492)

**Comment by Keridos** [comment]
forge 1492, that is unstable as far as I know. Try version 1448, that is the recommended one.

**Comment by Wolftein** [comment]
Oh sorry the server version is 1448, i was using 1492 on my client.

**Comment by Keridos** [comment]
This still looks like nothing we can fix on our end.

**Comment by Wolftein** [comment]
This is the KCauldron version i'm using: https://gitlab.prok.pw/Prototik/KCauldron. The issue started to happend after adding Mekanism. I'll try to scan for possible chunk corruption.

**Comment by Poenjabiesous** [comment]
This issue was fixed in 2.1.1 as far as I can remember. Also saw it once or twice.

**Comment by Poenjabiesous** [comment]
I can't confirm this at the moment.

**Comment by Keridos** [comment]
I do not see any code changes regarding this even remotely in the latest commits of this mod.

**Comment by Poenjabiesous** [comment]
It may be possible that I only saw it after the 2.1.1 commit, I'll look at this later.

**Comment by Keridos** [comment]
Please check if this still happens with 2.1.3

**Comment by Poenjabiesous** [comment]
This is fixed.
