### ISSUE TITLE
Open Modular Turrets crashes client when installed alongside Railcraft (Railcraft worked fine without it, though). Looking for missing EntityLocomotiveSteamMagic class...

### ISSUE THREAD

**Issue by Twilight13** [OpenModularTurretsTeam/OpenModularTurrets#147]
Open Modular Turrets crashes my Minecraft Client when I have Railcraft installed. If I remove Open Modular Turrets, everything works fine. If I remove Railcraft, everything works fine. But if both are installed together, the client crashes. The server, however, works fine with both installed.

This is with Minecraft 1.7.10, OpenModularTurrets-1.7.10-2.1.2-160, and Railcraft_1.7.10-9.6.1.0.

The crash is below:

Time: 7/27/15 8:15 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/railcraft/common/carts/EntityLocomotiveSteamMagic
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at com.creativemd.minecraftloader.ClientHelper.startGame(ClientHelper.java:260)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: mods/railcraft/common/carts/EntityLocomotiveSteamMagic
	at mods.railcraft.common.carts.EnumCart.<clinit>(EnumCart.java:47)
	at mods.railcraft.common.modules.ModuleCore.initFirst(ModuleCore.java:182)
	at mods.railcraft.common.modules.ModuleManager.initFirst(ModuleManager.java:254)
	at mods.railcraft.common.modules.ModuleManager.preInit(ModuleManager.java:174)
	at mods.railcraft.common.core.Railcraft.preInit(Railcraft.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.callMethod(MinecraftDummyContainer.java:209)
	at com.creativemd.minecraftloader.MinecraftDummyContainer.onModEvent(MinecraftDummyContainer.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 11 more
Caused by: java.lang.ClassNotFoundException: mods.railcraft.common.carts.EntityLocomotiveSteamMagic
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: thaumcraft/api/aspects/IAspectContainer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 49 more
Caused by: java.lang.ClassNotFoundException: thaumcraft.api.aspects.IAspectContainer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 53 more

**Comment by Keridos** [comment]
This has nothing to do with our mod, we do not even touch Railcraft and the log does not mention our mod at all.

**Comment by Poenjabiesous** [comment]
Yeah, I don't see any class in the stack used by OMT.

**Comment by Poenjabiesous** [comment]
Caused by: java.lang.ClassNotFoundException: mods.railcraft.common.carts.EntityLocomotiveSteamMagic

**Comment by Poenjabiesous** [comment]
AFAIK Open Modular Turrets runs alongside Railcraft in FTB Horizons 2 daybreaker and/or Trident, but I will need to confirm this.

**Comment by Keridos** [comment]
I can reproduce this though. But I suspect that this has still nothing to do with our mod since we do only optional load those interfaces.

**Comment by Keridos** [comment]
And now take a look at the changes I made @Poenjabiesous. Thanks to Player in IRC. Without him I never would have found this issue. Apparently that is a bug in FML, so has nothing to do with Railcraft, Thaumcraft and OMT.

**Comment by Keridos** [comment]
This is fixed in 2.1.3 btw. @Twilight13

**Comment by Twilight13** [comment]
FML, eh? OK, I thought I was just missing something really obvious, but I didn't understand why it was asking about Thaumcraft stuff when I didn't have it installed. Thanks for figuring this out. I really appreciate being able to use this OMT!
