### ISSUE TITLE
Shift clicking from Inventory into tier 1 turret base results in client+server crash

### ISSUE THREAD

**Issue by plazia** [OpenModularTurretsTeam/OpenModularTurrets#169]
Was playing single player and had a bunch of cobble in my inventory. More in my inventory than the tier 1 turret base could accomodate. I shift clicked the cobble to fill the inventory of the turret base and instacrash with the text - "shutting down internal server"

Client crash report http://hastebin.com/ixawejicop.coffee

Maybe this isn't an Open Modular Turrets issue but is in fact an NEI issue, nevertheless I thought I'd mention it since I was interacting with your turret at the time.

Keep up the good work - excellent mod.

**Comment by Poenjabiesous** [comment]
Hi plazia

Just to be 100% sure, I tried recreating the event. I was unable to. Shift clicking stacks into any turret base seems to work very well.

Looking at the stack trace, I can see that NEI tried to put a stack into a slot, but was unable to due to:

java.lang.NullPointerException: Updating screen events
	at com.google.common.collect.Iterables$3.transform(Iterables.java:512)
	at com.google.common.collect.Iterables$3.transform(Iterables.java:509)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543)
	at codechicken.nei.NEIClientUtils.giveStack(NEIClientUtils.java:155)
	at codechicken.nei.NEIClientUtils.giveStack(NEIClientUtils.java:140)
	at codechicken.nei.NEIClientUtils.cheatItem(NEIClientUtils.java:130)
	at codechicken.nei.NEIController.handleSlotClick(NEIController.java:138)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)

I am not sure, but I do not think that this is related to an issue on OMT.

**Comment by plazia** [comment]
Hi there.

Perhaps I wasn't fully descriptive enough in my text. I was ctrl+shift+clicking to put all the cobblestone in my inventory (of which I had several stacks) and then it crashed.

If that doesn't reproduce it for you then I guess it's probably an NEI thing. 

Thanks for looking into it.
plazia

**Comment by Poenjabiesous** [comment]
Ah, Ctrl-Shift-Click changes the entire scope of the problem and ticket. However, as the stack trace indicates, there is no failure on OMT's side. Since I do not know NEI integration well, I'll ask Keridos if he knows what is happening. But, nevertheless, my money is on an external environmental problem causing this.

**Comment by plazia** [comment]
Yeah I wasn't in creative mode however I was in survival with NEI cheat mode enabled. Perhaps that's relevant.

**Comment by Keridos** [comment]
Try it without cheat mode please.

**Comment by plazia** [comment]
Yes Inventory Tweaks is installed on both client and server.

**Comment by Keridos** [comment]
This is not NEI or OMT or vanilla minecraft, that is Inventory Tweaks doing the shift click thingie. Cannot even reproduce it without InvTweaks installed.

**Comment by Poenjabiesous** [comment]
Thanks for the investigation @Keridos
