### ISSUE TITLE
Client crashes when open Configure  turretbase GUI

### ISSUE THREAD

**Issue by Ksnz** [OpenModularTurretsTeam/OpenModularTurrets#197]
java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1027)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
	at net.minecraft.inventory.Container.func_75141_a(SourceFile:385)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1027)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:27)
	at net.minecraft.network.play.server.S2FPacketSetSlot.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Index'/230, l='MpServer', x=32,00, y=73,62, z=128,18]]
	Chunk stats: MultiplayerChunkCache: 399, 399
	Level seed: 0
	Level generator: ID 04 - RWG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (134,63,103), Chunk: (at 6,3,7 in 8,6; contains blocks 128,0,96 to 143,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 664647 game time, 677719 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 5 total; [EntityClientPlayerMP['Index'/230, l='MpServer', x=32,00, y=73,62, z=128,18], EntityBat['Ëåòó÷àÿ ìûøü'/43, l='MpServer', x=23,03, y=53,00, z=108,78], EntityCreeper['Êðèïåð'/44, l='MpServer', x=27,44, y=56,00, z=115,53], EntityCreeper['Êðèïåð'/45, l='MpServer', x=26,44, y=56,00, z=114,50], EntityEnderman['Ýíäåðìåí'/46, l='MpServer', x=32,66, y=54,00, z=116,38]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 576598688 bytes (549 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:MaxPermSize=128m -Xmn128M -Xmx1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_C1 92 mods loaded, 82 mods active
![161b471559 1](https://cloud.githubusercontent.com/assets/3342111/12069185/fe33b746-b033-11e5-88fa-e3cddedfd9f0.jpg)
Render that and crashes :disappointed:

**Comment by Keridos** [comment]
We cannot reproduce this here obviously since it works in all our instances. What exactly did you do, is your server in offline mode? Apparently that may be not an OMT bug since it crashes when you open the GUI and the inventory seems to be not synced to the server.

**Comment by Ksnz** [comment]
Server in online mode. There is no config button in GUI, if server is in offline mode. (UUID ownership bug probably)

**Comment by Ksnz** [comment]
Even without any mod http://pastebin.com/AQFGf5Sd
In singleplayer all works fine
My forge version is 1614

**Comment by Keridos** [comment]
Could you try downgrading forge to latest recommended version?

**Comment by Ksnz** [comment]
On  forge server 1588 all works fine. I will try to compile OMT for 1614.

**Comment by Ksnz** [comment]
I found that it's KCauldron problem and appears in another mods GUI too.
On simple forge 1614 all works fine, but on KCauldron not.
