### ISSUE TITLE
Exception report, NPE in openmodularturrets.tileentity.turretbase.TurretBaseTierTwoTileEntit 

### ISSUE THREAD

**Issue by ET-Bent** [OpenModularTurretsTeam/OpenModularTurrets#237]
OpenModularTurrets version: 1.7.10-2.2.2-217

This error occurs randomly from time to time and connot specifically be reproduced. If addiotional information is required, let me know.

```
[14:06:45 ERROR]: A TileEntity turretBaseOne(openmodularturrets.tileentity.turretbase.TurretBaseTierTwoTileEntity) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
    at openmodularturrets.tileentity.turretbase.TurretBase.readFromNBT_OpenComputers(TurretBase.java:369) ~[TurretBase.class:?]
    at li.cil.oc.common.asm.template.StaticSimpleEnvironment.readFromNBT(StaticSimpleEnvironment.java:74) ~[OpenComputers-MC1.7.10-1.6.0.3-rc.1-universal.jar:?]
    at openmodularturrets.tileentity.turretbase.TurretBase.func_145839_a(TurretBase.java:52) ~[TurretBase.class:?]
    at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:124) [aor.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:525) [aqk.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) [ChunkIOProvider.class:1.7.10-R0.1-SNAPSHOT]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-R0.1-SNAPSHOT]
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:1.7.10-R0.1-SNAPSHOT]
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:1.7.10-R0.1-SNAPSHOT]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:1.7.10-R0.1-SNAPSHOT]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:197) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:170) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:315) [ms.class:?]
    at net.minecraft.world.World.func_72964_e(World.java:751) [ahb.class:?]
    at net.minecraft.world.World.func_72849_a(World.java:1214) [ahb.class:?]
    at net.minecraft.world.World.
func_72849_a(World.java:1176) [ahb.class:?]
    at net.minecraft.world.World.func_72957_l(World.java:1166) [ahb.class:?]
    at org.bukkit.craftbukkit.v1_7_R4.block.CraftBlock.getLightLevel(CraftBlock.java:162) [CraftBlock.class:1.7.10-R0.1-SNAPSHOT]
    at org.bukkit.craftbukkit.v1_7_R4.block.CraftBlockState.<init>(CraftBlockState.java:41) [CraftBlockState.class:1.7.10-R0.1-SNAPSHOT]
    at org.bukkit.craftbukkit.v1_7_R4.block.CraftBlock.getState(CraftBlock.java:316) [CraftBlock.class:1.7.10-R0.1-SNAPSHOT]
    at org.bukkit.craftbukkit.v1_7_R4.CraftChunk.getTileEntities(CraftChunk.java:114) [CraftChunk.class:1.7.10-R0.1-SNAPSHOT]
    at com.earth2me.essentials.commands.Commandgc.run(Commandgc.java:68) [Essentials.jar:?]
    at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:186) [Essentials.jar:?]
    at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) [Essentials.jar:?]
    at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [Essentials.jar:?]
    at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) [Essentials.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-R0.1-SNAPSHOT]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-R0.1-SNAPSHOT]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
    at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
    at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
```

**Comment by Keridos** [comment]
Try newest version please.
