### ISSUE TITLE
Turret Particle Rendering Issue

### ISSUE THREAD

**Issue by darkshadow543** [OpenModularTurretsTeam/OpenModularTurrets#316]
Running on Turret Bases cause the game to crash, the error is a Null Pointer.
Short paste of crash report(not full crash).
java.lang.NullPointerException: Exception while adding particle
	at net.minecraft.world.World.func_189509_E(World.java:218)
	at net.minecraft.world.World.func_175625_s(World.java:2387)
	at omtteam.omlib.render.CamoBlockColor.func_186720_a(CamoBlockColor.java:22)
	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:167)
	at net.minecraft.client.particle.ParticleDigging.func_187154_b(SourceFile:52)
	at net.minecraft.client.particle.ParticleDigging.func_174845_l(SourceFile:47)

**Comment by Keridos** [comment]
Is this an issue with the newest builds?
