### ISSUE TITLE
Power expander crashes

### ISSUE THREAD

**Issue by purpleposeidon** [OpenModularTurretsTeam/OpenModularTurrets#317]
Got this crash on placing a RF power expander on a T5 turret base:

```

java.lang.NullPointerException: Exception ticking world
	at omtteam.omlib.tileentity.TileEntityElectric.func_189515_b(TileEntityElectric.java:47)
	at omtteam.omlib.tileentity.TileEntityContainer.func_189515_b(TileEntityContainer.java:29)
	at omtteam.openmodularturrets.tileentity.Expander.func_189515_b(Expander.java:38)
	at omtteam.omlib.tileentity.TileEntityBase.func_189518_D_(TileEntityBase.java:26)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:272)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```
Version 1.10.2-3.0.0-114

Here is the rest of the log: https://paste.ee/p/032Pp

**Comment by Keridos** [comment]
Thanks for the detailed report, Is fixed in next release.
