### ISSUE TITLE
Abstract Method Error

### ISSUE THREAD

**Issue by cjm721** [OpenModularTurretsTeam/OpenModularTurrets#329]
MC: 1.11.2
OMT: 3.0.0-146

Upon attempting to add a person as a trusted player to a turret the following exception occurs:
```[16:05:51] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method omtteam/openmodularturrets/tileentity/TurretBase.getWorld()Lnet/minecraft/world/World; is abstract
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.AbstractMethodError: Method omtteam/openmodularturrets/tileentity/TurretBase.getWorld()Lnet/minecraft/world/World; is abstract
        at omtteam.openmodularturrets.tileentity.TurretBase.getWorld(TurretBase.java) ~[TurretBase.class:?]
        at omtteam.omlib.tileentity.ITrustedPlayersManager.addTrustedPlayer(ITrustedPlayersManager.java:34) ~[ITrustedPlayersManager.class:?]
        at omtteam.openmodularturrets.network.messages.MessageAddTrustedPlayer$MessageHandlerAddTrustedPlayer.lambda$onMessage$9(MessageAddTrustedPlayer.java:31) ~[MessageAddTrustedPlayer$MessageHandlerAddTrustedPlayer.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more```

**Comment by Keridos** [comment]
yeah my bad

**Comment by Keridos** [comment]
Can you try this? https://jenkins.ironhide.de/job/OMLib%201.11.2/lastSuccessfulBuild/artifact/build/libs/omlib-1.11.2-3.0.0-87.jar

**Comment by cjm721** [comment]
Save error
```
[17:55:33] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method omtteam/openmodularturrets/tileentity/TurretBase.getWorld()Lnet/minecraft/world/World; is abstract
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.AbstractMethodError: Method omtteam/openmodularturrets/tileentity/TurretBase.getWorld()Lnet/minecraft/world/World; is abstract
	at omtteam.openmodularturrets.tileentity.TurretBase.getWorld(TurretBase.java) ~[TurretBase.class:?]
	at omtteam.omlib.tileentity.ITrustedPlayersManager.addTrustedPlayer(ITrustedPlayersManager.java:34) ~[ITrustedPlayersManager.class:?]
	at omtteam.openmodularturrets.network.messages.MessageAddTrustedPlayer$MessageHandlerAddTrustedPlayer.lambda$onMessage$9(MessageAddTrustedPlayer.java:31) ~[MessageAddTrustedPlayer$MessageHandlerAddTrustedPlayer.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by Keridos** [comment]
What about this one: https://jenkins.ironhide.de/job/OMLib%201.11.2/88/

**Comment by cjm721** [comment]
Still nope
```
[18:05:39] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Method omtteam/openmodularturrets/tileentity/TurretBase.getWorld()Lnet/minecraft/world/World; is abstract
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.AbstractMethodError: Method omtteam/openmodularturrets/tileentity/TurretBase.getWorld()Lnet/minecraft/world/World; is abstract
	at omtteam.openmodularturrets.tileentity.TurretBase.getWorld(TurretBase.java) ~[TurretBase.class:?]
	at omtteam.omlib.tileentity.ITrustedPlayersManager.addTrustedPlayer(ITrustedPlayersManager.java:34) ~[ITrustedPlayersManager.class:?]
	at omtteam.openmodularturrets.network.messages.MessageAddTrustedPlayer$MessageHandlerAddTrustedPlayer.lambda$onMessage$9(MessageAddTrustedPlayer.java:31) ~[MessageAddTrustedPlayer$MessageHandlerAddTrustedPlayer.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by Keridos** [comment]
that is super weird

**Comment by Keridos** [comment]
this? https://jenkins.ironhide.de/job/OMLib%201.11.2/89/artifact/build/libs/omlib-1.11.2-3.0.0-89.jar

**Comment by cjm721** [comment]
No exception now but no clue if it is adding the player as it still says "No Trusted Players to edit".

**Comment by cjm721** [comment]
Started up full running server and the player just had to be online. Might want to have notification for the user for that case. Other then that seems to be working now.

**Comment by Keridos** [comment]
Some small explanation. We use the UsernameCache from minecraft as the foundation to check if a player is a valid player. When you try to add a player, it scans through the usernamecache to see if the player is in there. You can view the usernamecache in your minecraft server folder. The user needs to be online at least once before you can add them to your trusted player list.

**Comment by cjm721** [comment]
Make sense. Might just want to tell the player something when it is null instead of it just not doing anything. Fast fix on the abstract method error 👍 .

Leaving closing this issue to you as don't know if you want to keep it open until you push a release / beta to curse.

**Comment by Keridos** [comment]
Will publish a beta in a few minutes, gonna close this for now, thanks for reporting 👍
