### ISSUE TITLE
On Connection

### ISSUE THREAD

**Issue by sfxworks** [OpenModularTurretsTeam/OpenModularTurrets#420]
On connection to my server I get the following stacktrace 

```
[17/5/2018 06:25:20 AM] [06:25:20] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: java.lang.NullPointerException
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at omtteam.openmodularturrets.handler.OMTEventHandler.worldLoadEvent(OMTEventHandler.java:140)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_744_OMTEventHandler_worldLoadEvent_Load.invoke(.dynamic)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at Reflector.call(Reflector.java:955)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at Reflector.postForgeBusEvent(Reflector.java:1182)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at Reflector.postForgeBusEvent(Reflector.java:1168)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:98)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:298)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17/5/2018 06:25:20 AM] [main/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:156]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

It does not crash the client, but it does come from STDERR. 
It may be a cause of connection issues upon logging in.

**Comment by Keridos** [comment]
Pretty sure you are not using the latest version.

**Comment by sfxworks** [comment]
Ya got me.
Using openmodularturrets-1.12.2-3.0.0-243
Ill throw the release in the pack.
