### ISSUE TITLE
Console spam when creating a new dimension

### ISSUE THREAD

**Issue by LemADEC** [OpenModularTurretsTeam/OpenModularTurrets#432]
As of 1.12.2-3.0.1-257, console is spammed with an irrelevant FileNotFoundException stacktrace whenever a new dimension is created:
```
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at java.io.FileInputStream.open0(Native Method)
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at java.io.FileInputStream.open(FileInputStream.java:195)
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at java.io.FileInputStream.<init>(FileInputStream.java:138)
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at omtteam.openmodularturrets.handler.OMTEventHandler.worldLoadEvent(OMTEventHandler.java:144)
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_609_OMTEventHandler_worldLoadEvent_Load.invoke(.dynamic)
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:309)
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[06:40:33] [Server thread/INFO] [STDERR]: [omtteam.openmodularturrets.handler.OMTEventHandler:worldLoadEvent:159]:      at java.lang.Thread.run(Thread.java:748)
```

**Comment by Keridos** [comment]
Already fixed in dev env.
