### ISSUE TITLE
Placing Turret base causes render issue

### ISSUE THREAD

**Issue by LordMZTE** [OpenModularTurretsTeam/OpenModularTurrets#465]
placing a turret base will sometimes make nearby blocks not render
and it puts this error in the log

[11:25:09] [Chunk Batcher 12/ERROR] [CodeChickenLib]: 
 CCL has caught an exception whilst rendering a block
  BlockPos:      x:2316, y:71, z:-9936
  Block Class:   class crazypants.enderio.conduits.conduit.BlockConduitBundle
  Registry Name: enderio:block_conduit_bundle
  Metadata:      0
  State:         enderio:block_conduit_bundle[opaque=false]
 Tile at position
  Tile Class:    class crazypants.enderio.conduits.conduit.TileConduitBundle
  Tile Id:       enderio:tile_conduit_bundle
  Tile NBT:      {conduits:{size:0},paintSource-:1b,ForgeData:{SpongeData:{}},x:2316,y:71,ForgeCaps:{},facadeType:0,z:-9936,id:"enderio:tile_conduit_bundle"}
You can turn off player messages in the CCL config file.

net.minecraft.util.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at mrtjp.projectred.relocation.MovingBlockRenderDispatcher.func_175018_a(renders.scala:275) [MovingBlockRenderDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException

**Comment by Keridos** [comment]
Version?

**Comment by LordMZTE** [comment]
> 
> 
> Version?

sorry i forgot its 3.1.0-306

i just placed my turret base down and it causes this bug and also makes some nearby blocks (i cant see a pattern) invisible
with the render error catching feature disabled in the code chicken lib config it causes minecraft to crash

**Comment by Quisquid** [comment]
Is there any progress on solving this issue? 

It seems that "Better foliage" mod is causing this render error. If i exclude better foliage from my mod folder everything works fine for me.

**Comment by Keridos** [comment]
I have not yet been able to reproduce any of this.

**Comment by Quisquid** [comment]
I am narrowing it down which of my other mods is guilty, cause if i only use OMT this does not happen.
Found your Discord yesterday, will contact you there if i have further information.

**Comment by theron61** [comment]
In my case it looks like it is the .isTranslucent check that is inducing the behavior:

I can confirm it looks like Optifine is the contributing factor.

---



net.minecraft.util.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:95) ~[bvm.class:?]
	at codechicken.lib.render.block.CCBlockRendererDispatcher.renderBlock(CCBlockRendererDispatcher.java:82) [CCBlockRendererDispatcher.class:?]
	at gcewing.sg.BaseAORenderingManager$CustomBlockRendererDispatcher.renderBlock(BaseAORenderingManager.java:85) [BaseAORenderingManager$CustomBlockRendererDispatcher.class:?]
	at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:328) [bxr.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(SourceFile:100) [bxn.class:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43) [bxn.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at omtteam.openmodularturrets.blocks.BlockTurretBase.isTranslucent(BlockTurretBase.java:151) ~[BlockTurretBase.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.isTranslucent(BlockStateContainer.java:327) ~[awu$a.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.updateVertexBrightness(BlockModelRenderer.java:673) ~[bvo$b.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:190) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:128) ~[bvo.class:?]
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[ForgeBlockModelRenderer.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:79) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:58) ~[bvo.class:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:80) ~[bvm.class:?]

**Comment by Keridos** [comment]
Then it seems as optifine is messing up our blockstates. I have no idea why it should do that. and I cannot see any way how this could actually have an NPE.

Could you try this build? https://jenkins.ironhide.de/job/OMTTeam/job/OpenModularTurrets-1.12/321/
