### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by anatoliy99** [OpenModularTurretsTeam/OpenModularTurrets#468]
When I break a block near the turret, minecraft crashes.
It would also not be bad if you had somewhere written about how many turrets can be put on the base.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 2/4/19 8:36 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at omtteam.openmodularturrets.blocks.BlockTurretBase.func_149751_l(BlockTurretBase.java:151)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185895_e(BlockStateContainer.java:327)
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.func_187491_a(BlockModelRenderer.java:660)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:189)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:115)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:89)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:78)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:57)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:174)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1482)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1730)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at omtteam.openmodularturrets.blocks.BlockTurretBase.func_149751_l(BlockTurretBase.java:151)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185895_e(BlockStateContainer.java:327)
	at net.minecraft.client.renderer.BlockModelRenderer$AmbientOcclusionFace.func_187491_a(BlockModelRenderer.java:660)
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:189)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:115)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:89)

-- Block model being tesselated --
Details:
	Block: minecraft:leaves[check_decay=true,decayable=true,variant=oak]
	Block location: World: (42,79,42), Chunk: (at 10,4,10 in 2,2; contains blocks 32,0,32 to 47,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:78)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:57)

-- Block being tesselated --
Details:
	Block type: ID #18 (tile.leaves // net.minecraft.block.BlockOldLeaf // minecraft:leaves)
	Block data value: 8 / 0x8 / 0b1000
	Block location: World: (42,79,42), Chunk: (at 10,4,10 in 2,2; contains blocks 32,0,32 to 47,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:174)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:1482)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1730)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['demonseeker'/1026, l='MpServer', x=43.30, y=80.00, z=42.67]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (40,64,40), Chunk: (at 8,4,8 in 2,2; contains blocks 32,0,32 to 47,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1174 game time, 1174 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 71 total; [EntitySpider['Паук'/4159, l='MpServer', x=-30.50, y=28.00, z=36.50], EntityCow['Корова'/64, l='MpServer', x=-15.50, y=84.00, z=-1.50], EntityCow['Корова'/65, l='MpServer', x=-14.80, y=78.00, z=-5.51], EntityCow['Корова'/66, l='MpServer', x=-20.68, y=76.00, z=-4.70], EntityCow['Корова'/67, l='MpServer', x=-18.60, y=78.00, z=-3.45], EntityCow['Корова'/68, l='MpServer', x=-18.50, y=107.00, z=72.50], EntityCow['Корова'/69, l='MpServer', x=-18.50, y=108.00, z=73.50], EntityCow['Корова'/70, l='MpServer', x=-19.50, y=107.00, z=72.50], EntityCow['Корова'/71, l='MpServer', x=-15.81, y=114.00, z=78.47], EntityCow['Корова'/80, l='MpServer', x=17.50, y=109.00, z=86.50], EntityCow['Корова'/81, l='MpServer', x=15.50, y=110.00, z=86.55], EntityCow['Корова'/82, l='MpServer', x=15.50, y=110.00, z=85.59], EntityCow['Корова'/83, l='MpServer', x=16.50, y=109.00, z=83.50], EntityCow['Корова'/96, l='MpServer', x=47.50, y=80.00, z=95.50], EntityCow['Корова'/97, l='MpServer', x=48.50, y=80.00, z=95.50], EntityCow['Корова'/98, l='MpServer', x=47.50, y=80.00, z=98.50], EntityCow['Корова'/99, l='MpServer', x=44.50, y=80.00, z=94.50], EntityZombie['Зомби'/4197, l='MpServer', x=-29.50, y=28.00, z=36.50], EntityCow['Корова'/120, l='MpServer', x=76.50, y=72.00, z=3.50], EntityCow['Корова'/121, l='MpServer', x=77.50, y=72.00, z=3.50], EntityCow['Корова'/122, l='MpServer', x=77.50, y=71.00, z=5.50], EntityCow['Корова'/123, l='MpServer', x=73.50, y=70.00, z=6.50], EntityCreeper['Крипер'/4230, l='MpServer', x=-29.50, y=39.00, z=55.50], EntityZombie['Зомби'/4241, l='MpServer', x=-16.50, y=37.00, z=111.50], EntityPig['Свинья'/147, l='MpServer', x=105.50, y=87.00, z=-36.50], EntityPig['Свинья'/148, l='MpServer', x=110.49, y=94.00, z=-36.67], EntityCow['Корова'/150, l='MpServer', x=111.50, y=77.00, z=-28.50], EntityCow['Корова'/151, l='MpServer', x=110.50, y=81.00, z=-30.50], EntityCow['Корова'/152, l='MpServer', x=109.50, y=86.00, z=-32.50], EntityCow['Корова'/153, l='MpServer', x=107.50, y=90.00, z=-35.50], EntityZombie['Зомби'/4250, l='MpServer', x=-18.50, y=16.00, z=-25.50], EntityZombie['Зомби'/4256, l='MpServer', x=-22.25, y=28.00, z=37.50], EntitySheep['Овца'/163, l='MpServer', x=118.36, y=106.00, z=-17.34], EntityCreeper['Крипер'/4301, l='MpServer', x=-31.50, y=13.00, z=-29.50], EntityBat['Летучая мышь'/4302, l='MpServer', x=-33.55, y=43.05, z=63.37], EntityZombie['Зомби'/4309, l='MpServer', x=-21.50, y=15.00, z=-25.50], EntityZombie['Зомби'/4329, l='MpServer', x=-18.50, y=43.00, z=108.50], EntityCreeper['Крипер'/4335, l='MpServer', x=-19.50, y=47.00, z=21.50], EntityBat['Летучая мышь'/4351, l='MpServer', x=-17.47, y=22.26, z=31.92], EntityZombie['Зомби'/4376, l='MpServer', x=-27.50, y=14.00, z=-26.50], EntityBat['Летучая мышь'/4380, l='MpServer', x=-17.41, y=46.22, z=110.52], EntityEnderman['Эндермен'/4388, l='MpServer', x=-18.50, y=41.00, z=116.50], EntityBat['Летучая мышь'/4393, l='MpServer', x=-11.08, y=38.52, z=48.83], EntityZombie['Зомби'/4404, l='MpServer', x=-33.50, y=28.00, z=29.50], EntityCreeper['Крипер'/4426, l='MpServer', x=-20.50, y=41.00, z=120.50], EntityCreeper['Крипер'/4428, l='MpServer', x=-20.50, y=41.00, z=111.50], EntitySkeleton['Скелет'/4437, l='MpServer', x=-18.50, y=15.00, z=-22.50], EntityCreeper['Крипер'/4441, l='MpServer', x=-19.50, y=15.00, z=-24.50], EntityCreeper['Крипер'/4442, l='MpServer', x=-17.50, y=15.00, z=-23.50], EntityCreeper['Крипер'/4450, l='MpServer', x=-19.49, y=47.00, z=25.82], EntityCreeper['Крипер'/4455, l='MpServer', x=-24.50, y=26.00, z=120.50], EntityCreeper['Крипер'/4466, l='MpServer', x=-19.50, y=38.00, z=54.50], EntitySkeleton['Скелет'/4472, l='MpServer', x=-18.50, y=38.00, z=53.50], EntityZombie['Зомби'/4478, l='MpServer', x=-22.50, y=41.00, z=48.50], EntityZombie['Зомби'/4480, l='MpServer', x=-33.55, y=39.00, z=58.26], EntitySkeleton['Скелет'/4481, l='MpServer', x=-25.27, y=38.00, z=54.36], EntitySkeleton['Скелет'/4482, l='MpServer', x=-27.50, y=38.00, z=52.50], EntitySkeleton['Скелет'/4504, l='MpServer', x=-17.50, y=111.00, z=100.50], EntityZombie['Зомби'/4507, l='MpServer', x=-22.95, y=28.00, z=37.50], EntityZombie['Зомби'/4508, l='MpServer', x=-10.75, y=111.00, z=106.46], EntityZombie['Зомби'/4509, l='MpServer', x=-16.50, y=111.00, z=102.50], EntityBat['Летучая мышь'/4524, l='MpServer', x=-22.57, y=14.02, z=-28.20], EntityItem['item.tile.doublePlant.rose'/4525, l='MpServer', x=56.27, y=74.00, z=-7.39], EntityBat['Летучая мышь'/4538, l='MpServer', x=-16.66, y=28.53, z=115.53], EntityBat['Летучая мышь'/4540, l='MpServer', x=-8.64, y=25.08, z=120.95], EntitySkeleton['Скелет'/4560, l='MpServer', x=-24.50, y=40.00, z=121.50], EntityCreeper['Крипер'/4565, l='MpServer', x=-20.50, y=40.00, z=117.50], EntityCreeper['Крипер'/4576, l='MpServer', x=-22.50, y=40.00, z=119.50], EntityBat['Летучая мышь'/4582, l='MpServer', x=-20.63, y=16.04, z=-24.44], EntityBat['Летучая мышь'/4586, l='MpServer', x=-33.71, y=22.47, z=35.47], EntityPlayerSP['demonseeker'/1026, l='MpServer', x=43.30, y=80.00, z=42.67]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 329711912 bytes (314 MB) / 657629184 bytes (627 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 5 total; -Xmx3072M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E1 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                 | Version      | Source                                  | Signature                                |
	|:--------- |:------------------ |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft          | 1.12.2       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp                | 9.42         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML                | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge              | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | omlib              | 3.1.0-208    | omlib-1.12.2-3.1.0-208.jar              | None                                     |
	| UCHIJAAAA | openmodularturrets | 3.1.0-306    | openmodularturrets-1.12.2-3.1.0-306.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 750/PCIe/SSE2'
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: laacis2's Natural 2k+.zip
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.82
	OpenGlRenderer: GeForce GTX 750/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by Keridos** [comment]
Can you try the dev builds? This build works fine on our test server and in my dev env.
