### ISSUE TITLE
ArrayIndexOutOfBoundsException upon loading chunks

### ISSUE THREAD

**Issue by LemADEC** [OpenModularTurretsTeam/OpenModularTurrets#537]
#### Issue Description:

Server crash when player loads chunk with a placed relativistic turret.

Note: due to version dependencies with ompd-1.12.2-3.1.0-73, we're stuck on OMT 1.12.2-3.2.0-370 which seems to be no longer maintained.  I'm not sure what our upgrade options are without breaking existing saves.

#### What happens:
java.lang.ArrayIndexOutOfBoundsException: 4
    at omtteam.openmodularturrets.tileentity.turrets.TurretHead.func_189515_b(TurretHead.java:85)
    at omtteam.omlib.tileentity.TileEntityBase.func_189517_E_(TileEntityBase.java:48)
    at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

#### What you expected to happen:
No crash

#### Steps to reproduce:

1. Unknown at this time

____
#### Affected Versions (Do *not* use "latest"):

- OMT: 1.12.2-3.2.0-370
- OMLib: 1.12.2-3.2.0-254
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- SpongeForge? yes
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

Private messages only since it's a competitive servers, we don't want to expose players' coordinates

**Comment by Keridos** [comment]
Is OMPD holding you back on upgrading? If yes, that needs to be fixed by me.

**Comment by LemADEC** [comment]
It was some time ago, from what I remember OMPD 3.1.1 was never released after fixing https://github.com/OpenModularTurretsTeam/OpenModularPassiveDefense/issues/29

**Comment by Keridos** [comment]
Oh wow, yeah the build failed. Fixed now, build is up on curseforge https://www.curseforge.com/minecraft/mc-mods/ompd/files/3085585
