### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by qqqZXzz123** [OpenModularTurretsTeam/OpenModularTurrets#543]
After installing the turret unit, the server crashed instantly,

After loading the chunk, the server crashed.

```
[18:14:13] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 61 mods : buildcraftlib@7.99.24.7,asielib@1.0.0,openmods@0.12.2,buildcraftenergy@7.99.24.7,jei@4.16.1.301,damageindicatorsmod@1.0,buildcrafttransport@7.99.24.7,cofhcore@4.6.6,thermalfoundation@2.6.7,opencomputers@1.7.5.192,mcp@9.42,journeymap@1.12.2-5.7.0,appliedenergistics2@rv6-stable-7,microblockcbe@2.6.2.83,inventorytweaks@1.64+dev.151.822d839,foamfixcore@7.7.4,omlib@3.2.0-256,projectred-illumination@4.9.4.120,secretroomsmod@5.6.4,cofhworld@1.4.0,waila@1.8.26,computronics@1.6.6,galacticraftplanets@4.0.2.281,micdoodlecore@,projectred-compat@1.0,forge@14.23.5.2854,openmodularturrets@3.2.0-374,buildcraftrobotics@7.99.24.7,ironchest@1.12.2-7.0.67.844,openblocks@1.8.1,minecraft@1.12.2,tconstruct@1.12.2-2.13.0.183,tinkertoolleveling@1.12.2-1.1.0.DEV.b23e769,redstoneflux@2.1.1,buildcraftsilicon@7.99.24.7,openmodscore@0.12.2,projectred-relocation@4.9.4.120,srm-hooks@1.12.2-1.0.0,projectred-core@4.9.4.120,vanillafix@1.0.10-150,mantle@1.12-1.3.3.55,buildcraftbuilders@7.99.24.7,buildcraftfactory@7.99.24.7,galacticraftcore@4.0.2.281,projectred-transmission@4.9.4.120,mrtjpcore@2.1.4.43,projectred-expansion@4.9.4.120,projectred-transportation@4.9.4.120,projectred-exploration@4.9.4.120,FML@8.0.99.99,thermalexpansion@5.5.7,projectred-integration@4.9.4.120,buildcraftcompat@7.99.24.7,aiimprovements@0.0.1.1,minecraftmultipartcbe@2.6.2.83,forgemultipartcbe@2.6.2.83,foamfix@0.10.11-1.12.2,opencomputers|core@1.7.5.192,backpack@3.0.2,codechickenlib@3.2.3.358,buildcraftcore@7.99.24.7
[18:14:13] [Netty Server IO #1/INFO] [journeymap]: CLIENT
[18:14:13] [Netty Server IO #1/INFO] [CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config.
[18:14:14] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[18:14:14] [Server thread/INFO] [minecraft/PlayerList]: qqqZXzz123[/25.4.46.240:13912] logged in with entity id 0 at (112.21015394426061, 63.0, 477.48442446796116)
[18:14:14] [Server thread/INFO] [minecraft/DedicatedServer]: qqqZXzz123 joined the game
[18:14:14] [Server thread/INFO] [OpenComputers]: Successfully patched net/minecraft/entity/EntityLiving.recreateLeash.
[18:14:14] [Server thread/INFO] [Waila]: Player GCEntityPlayerMP['qqqZXzz123'/0, l='world', x=112,21, y=63,00, z=477,48] connected. Sending ping
[18:14:16] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at omtteam.openmodularturrets.tileentity.turrets.TurretHead.writeToNBT(TurretHead.java:84) ~[TurretHead.class:?]
        at omtteam.openmodularturrets.tileentity.turrets.AbstractDirectedTurret.writeToNBT(AbstractDirectedTurret.java:52) ~[AbstractDirectedTurret.class:?]
        at omtteam.openmodularturrets.tileentity.turrets.AbstractDirectedTurret.getUpdatePacket(AbstractDirectedTurret.java:38) ~[AbstractDirectedTurret.class:?]
        at net.minecraft.server.management.PlayerChunkMapEntry.sendBlockEntity(PlayerChunkMapEntry.java:288) ~[ot.class:?]
        at net.minecraft.server.management.PlayerChunkMapEntry.update(PlayerChunkMapEntry.java:250) ~[ot.class:?]
        at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:115) ~[ou.class:?]
        at net.minecraft.world.WorldServer.tick(WorldServer.java:227) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
        ... 4 more
[18:14:16] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\Богдан\Downloads\1122server2021\.\crash-reports\crash-2021-02-06_18.14.16-server.txt
[18:14:16] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[18:14:16] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[18:14:16] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[18:14:16] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/overworld
[18:14:17] [Server thread/ERROR] [FML]: A TileEntity type omtteam.openmodularturrets.tileentity.turrets.DisposableItemTurretTileEntity has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.NullPointerException: null
        at omtteam.openmodularturrets.tileentity.turrets.TurretHead.writeToNBT(TurretHead.java:84) ~[TurretHead.class:?]
        at omtteam.openmodularturrets.tileentity.turrets.AbstractDirectedTurret.writeToNBT(AbstractDirectedTurret.java:52) ~[AbstractDirectedTurret.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.writeChunkToNBT(AnvilChunkLoader.java:383) [aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.saveChunk(AnvilChunkLoader.java:174) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.saveChunkData(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.saveChunks(ChunkProviderServer.java:230) [on.class:?]
        at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1007) [oo.class:?]
        at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:408) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:446) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[18:14:17] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'world'/Storage Cell
[18:14:17] [Server thread/INFO] [FML]: Unloading dimension 0
[18:14:17] [Server thread/INFO] [FML]: Unloading dimension 2
[18:14:17] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -30
[18:14:17] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -29
[18:14:17] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -31
[18:14:17] [Server thread/INFO] [Galacticraft]: Unregistered Dimension: -28
[18:14:17] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[18:14:17] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
[18:14:17] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Saving players
```

**Comment by Keridos** [comment]
Noted.
Please upload the crashlog at gist.github.,com or some other paste site and paste the link and also use the template for the report.

**Comment by Keridos** [comment]
@qqqZXzz123 could you test if this fixes it?
[mods.zip](https://github.com/OpenModularTurretsTeam/OpenModularTurrets/files/6048036/mods.zip)

**Comment by qqqZXzz123** [comment]
I uninstalled the mod.
