### ISSUE TITLE
ArrayIndexOutOfBoundsException upon loading chunks

### ISSUE THREAD

**Issue by LemADEC** [OpenModularTurretsTeam/OpenModularTurrets#552]
#### Issue Description:

Server crash when player loads chunk with a placed turret.

Note: it seems related to #537, through I'm unable to confirm if it's a relativistic turret or not.

#### What happens:

Server crash

#### What you expected to happen:

No crash

#### Steps to reproduce:

1. Player joining in existing base
2. (unknown turret details at this time)

____
#### Affected Versions (Do *not* use "latest"):

- OMT: openmodularturrets-1.12.2-3.2.0-379
- OMLib: omlib-1.12.2-3.2.0-256
- OMPD: ompd-1.12.2-3.2.0-76
- Minecraft: 1.12.2
- Forge: Forge 14.23.5.2855
- SpongeForge? yes, spongeforge-1.12.2-2838-7.3.0
- Optifine? no
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

```
Description: Exception ticking world

java.lang.ArrayIndexOutOfBoundsException: 4
    at omtteam.openmodularturrets.tileentity.turrets.TurretHead.func_189515_b(TurretHead.java:91)
    at omtteam.omlib.tileentity.TileEntityBase.func_189517_E_(TileEntityBase.java:48)
    at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Keridos** [comment]
If this still happens, feel free to reopen this

**Comment by LemADEC** [comment]
Relativistic turrets have been disabled so they were probably the source of that problem
